### ISSUE TITLE
play button

### ISSUE THREAD

**Issue by haythamodeh** [Benmoony/TeamFAM_Final#9]
the play button on homepage does not funtion.

needs to navigate to the game

![bug_screenshot](https://cloud.githubusercontent.com/assets/25089880/26170230/86b075bc-3af5-11e7-88bf-425dc2dcea07.PNG)

**Comment by MikeTheGreat** [comment]
A little more detail would be good.

Maybe include the URL for the home page, so it's crystal clear which page you're talking about?

**Comment by Benmoony** [comment]
This will be implemented after game is added to .NET CORE APPLICATION
